Tags
cucumber/cucumber.ml pull request #17
Opened 2018-04-22 19:23 UTC by cyocum

This adds simple tag support for the instance where certain tags are allowed or disallowed based on the user's preferences as set on the command-line.  Additionally, this adds support for running multiple feature files from the command line.

2018-04-23 08:42 UTC, Thegaram commented
@cyocum Would you mind providing a simple example for this, e.g. a simple feature file with tags and the command to run it?

2018-04-23 10:29 UTC, cyocum commented
Yes, sorry! I was excited to get this out the door last night.

```gherkin
Feature: Cucumber.ml test

  @a
  Scenario: simple docstring
    Given a simple DocString
    When I run my test
    Then I should receive the test results

  @b
  Scenario: another test
    Given DocString with alternative separator inside
    When I run my other test
    Then I should receive the different test results
```
After you compile you should be able to do this with the gherkin above in a file named `test.feature`:

```
./cucumber_run --tags "@a ~@b" test.feature
```

This should run the scenario tagged as "@a" and not run the scenario marked "@b".

Additionally, you should be able to do:

```
./cucumber_run test.feature test_2.feature
```

and then have those feature files run together

2018-04-23 13:17 UTC, Thegaram commented
Thanks!

Seems like you forgot to commit the file `tag.mli`. Please add it so that I can test your solution.

Also, there is a typo in `runnable_pickel_lst` (should be `runnable_pickle_lst`).

2018-04-23 13:55 UTC, cyocum commented
Arg! Thanks! I have updated accordingly. I hate it when I do that.

2018-04-23 14:15 UTC, Thegaram requested changes
The basic behavior seems fine. Some suggestions:

- I get a segfault if I forget to specify the feature file. It would be nicer to output an understandable error message in this case.

- The order of pickle/feature file execution is reversed. For example, `./cucumber_run test1.feature test2.feature`, first it runs `test2` and then `test1`, which is counter-intuitive.

- I think you should either write the feature name before each feature output, or output the execution results together for all feature files.

- Small suggestion for the Reporting module: instead of `0 scenarios ()` it would be nicer to write `0 scenarios`.

2018-04-23 14:43 UTC, cyocum commented
Great! Thank you! I will get on those.

2018-04-23 15:34 UTC, cyocum commented
I also fixed the list reversal in my last commit.

2018-04-24 08:04 UTC, Thegaram commented
Yeah, thanks, the things I mentioned are fixed now. Some more suggestions:

- It would be nice to separate feature file outputs using an empty line. The current output looks like this:

```
...
Feature File: test1.feature
3 scenarios (1 undefined, 2 passed)
9 steps (1 undefined, 2 skipped, 6 passed)
...U--...
Before step
Given
...
```

Maybe in the future we could borrow the output format of a more mature Cucumber implementation.

- I get a build warning for clean builds, not sure if it's a problem:

```
$ make build_library
ocamlfind opt -g -I /usr/include/gherkin -I lib/ -cclib -lgherkin -o lib/gherkin_intf.o lib/gherkin_intf.c 
ocamlfind opt -c -I lib/ -for-pack Cucumber -package re,re.perl,base -c lib/location.mli lib/docstring.mli lib/table.ml lib/step.mli lib/outcome.mli lib/tag.mli lib/pickle.mli lib/report.mli lib/lib.mli
File "_none_", line 1:
Warning 58: no cmx file was found in path for module Location, and its interface was not compiled with -opaque
```

- Is it necessary to use mutable references for argument parsing?

2018-04-24 09:36 UTC, cyocum commented
> Maybe in the future we could borrow the output format of a more mature Cucumber implementation.

There are some movement on this front with a "universal pickle runner" which were demo'ed at the Cukenfest hackday last weekend.  Right now, I think we may want to refactor `report.ml` to use the [Format](https://caml.inria.fr/pub/docs/manual-ocaml/libref/Format.html) module which I think might give a better experience of text output.

> Is it necessary to use mutable references for argument parsing?

Unfortunately, I believe so :(.  The other library for dealing with this is [getopt](https://github.com/mcandre/ocaml-getopt/blob/master/sample.ml) and it is the same.  There is also [getopts](https://github.com/michipili/getopts) which seems more functional but does not have any examples that I could find to draw on to understand how it works.  The other that many use is [Cmdliner](http://erratique.ch/software/cmdliner/doc/Cmdliner), which I do not yet understand how to use.

2018-04-24 09:41 UTC, Thegaram commented
I think it would make more sense to put an empty line after the pickle stats, i.e.

```ocaml
let print feature_file outcome_lists =
  let outcomes = List.flatten outcome_lists in
  print_endline ("Feature File: " ^ feature_file);
  print_scenario_report outcome_lists;
  print_step_report outcomes;
  Outcome.print_outcomes outcomes;
  print_newline (); print_newline () 
```

Current output:

```
$ ./cucumber_run test1.feature test2.feature 
Before step
Given
When
my state is true
Then
my state is false
After step
Before step
Could not find step: DocString with alternative separator inside
After step
Before step
Given
When
my state is true
Then
my state is false
After step

Feature File: test1.feature
3 scenarios (1 undefined, 2 passed)
9 steps (1 undefined, 2 skipped, 6 passed)
...U--...
Before step
Given
When
my state is true
Then
my state is false
After step
Before step
Could not find step: DocString with alternative separator inside
After step
Before step
Given
When
my state is true
Then
my state is false
After step

Feature File: test2.feature
3 scenarios (1 undefined, 2 passed)
9 steps (1 undefined, 2 skipped, 6 passed)
...U--...
```

It should be easy to see which output belongs to which test file / pickle stats.

2018-04-24 09:47 UTC, Thegaram approved these changes

2018-04-24 09:53 UTC, merged